version: '3.5'

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '35729:35729'
    environment:
      - NODE_ENV=development
