# Generated by Django 2.2 on 2019-04-15 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprayer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprayApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('spray', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sprayer.Spray')),
            ],
        ),
    ]
