# Generated by Django 2.2 on 2019-04-17 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprayer', '0003_auto_20190416_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprayapplication',
            name='field',
        ),
        migrations.AddField(
            model_name='sprayapplication',
            name='field_season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sprayer.FieldSeason'),
            preserve_default=False,
        ),
    ]
