# Generated by Django 2.1.7 on 2019-04-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprayer', '0006_auto_20190424_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
