# Generated by Django 2.1.7 on 2019-04-24 14:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sprayer', '0008_auto_20190424_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
