# Generated by Django 2.1.7 on 2019-04-25 00:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sprayer', '0012_auto_20190425_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
