# Generated by Django 2.1.7 on 2019-04-25 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sprayer', '0015_auto_20190425_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='user',
        ),
        migrations.AddField(
            model_name='owner',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='owner',
            unique_together={('name', 'user')},
        ),
    ]
