# Generated by Django 2.1.7 on 2019-04-25 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprayer', '0018_auto_20190425_0049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprayapplication',
            old_name='cost',
            new_name='price',
        ),
        migrations.AddField(
            model_name='sprayapplication',
            name='amount_unit',
            field=models.CharField(choices=[('OUNCES', 'Ounces'), ('GALLONS', 'Gallons'), ('LITERS', 'Liters')], default='OUNCES', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sprayapplication',
            name='price_unit',
            field=models.CharField(choices=[('OUNCES', 'Ounces'), ('GALLONS', 'Gallons'), ('LITERS', 'Liters')], default='OUNCES', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='owner',
            unique_together=set(),
        ),
    ]
